### ISSUE TITLE
Saved prefs.dat file has error upon loading

### ISSUE THREAD

**Issue by sturgman** [trisyoungs/aten#15]
aten: 2.1, windows: 7
I saved the default configuration as a prefs.dat file without changing any of the defaults. Aten creates the file C:\users\username\aten\prefs.dat with contents:

`
// Element Data
// Program Preferences
`
When I restart aten I get the following in the console:

Error occurred here (line 2 in file 'C:\Users\sturgmancohen\aten\prefs.dat'):

 ^

And reports that preference file not found.

**Comment by alinelena** [comment]
reproduced it on linux too.. it seems not to like prefs files with comments only.

Alin

**Comment by alinelena** [comment]
OK I see what happens on empty or comment only files yyparse returns error... 
probably as a trick save shall dump at least one preference...
Alin

**Comment by trisyoungs** [comment]
Changed the main lexer to 'accept' when encountering EOF, so now empty command files are valid (fixed in 8789e95f14cdf1336673bc0a758bd4e6ae67fd26).
