### ISSUE TITLE
comma instead of point as decimal separator in output files

### ISSUE THREAD

**Issue by janknaupato** [trisyoungs/aten#23]
On Ubuntu Xenial (16.4) compiled with Qt 5.5.1, at least .xyz, .pdb and .mol2 output uses "," instead of "." as decimal separator, e.g.:

mol2:
@<TRIPOS>MOLECULE
PDB Model
3   0

SMALL
NO_CHARGES
Coordinates churned out by Aten

@<TRIPOS>ATOM
     1      O     5,00000     9,20600    14,08800      O

     2      H     5,43000     9,96700    13,49700      H

     3      H     5,31900     9,36200    14,99300      H

PDB:

REMARK Aten-created PDB
TITLE  PDB Model
CRYST1    1,000    1,000    1,000  90,00  90,00  90,00         P 1   1

ATOM  1     O0   MOL  0          5,000   9,206  14,088  1,00  1,00           O
ATOM  2     H0   MOL  1          5,430   9,967  13,497  1,00  1,00           H
ATOM  3     H0   MOL  1          5,319   9,362  14,993  1,00  1,00           H
TER
END

XYZ:

3
PDB Model
O             5,000000     9,206000    14,088000     0,000000
H             5,430000     9,967000    13,497000     0,000000
H             5,319000     9,362000    14,993000     0,000000

The problem seems to be caused by Qt localization settings.

**Comment by trisyoungs** [comment]
Have added what I think is a fix in the latest commit (6e4749fb5e33bc56ec71ef981b69149717069150).  Let me know if it corrects the number format on your system.

**Comment by janknaupato** [comment]
Yes, that fixed the problem. Thank you very much!
